### ISSUE TITLE
cool design

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/react-only-intern-23#15]
Download this template and convert it into react application
https://codyhouse.co/demo/schedule-template/index.html

**Comment by sanchit94** [comment]
Alright I'll work on this first thing in the morning. Going to sleep now!!

**Comment by atherdon** [comment]
have a good night


On 17-Jun-2018 at 09:47 PM, Sanchit Sharma wrote:


Alright I'll work on this first thing in the morning. Going to sleep now!!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/react-only-intern-23/issues/15#issuecomment-397908779>,
or mute the thread

**Comment by sanchit94** [comment]
@atherdon  Okay so I am on it and I think I will have to use react-bootstrap for this.

**Comment by atherdon** [comment]
try react-strap for this. it's use Bootstrap 4. maybe we'll need to make
some adjustments, but it's ok


On 18-Jun-2018 at 08:37 AM, Sanchit Sharma wrote:


@atherdon <https://github.com/atherdon> Okay so I am on it and I think I
will have to use react-bootstrap for this.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/react-only-intern-23/issues/15#issuecomment-397981937>,
or mute the thread

**Comment by atherdon** [comment]
@sanchit94 I like it! looks more organized that it was before

**Comment by sanchit94** [comment]
@atherdon Completed the data part and pushed the code, just check.

**Comment by sanchit94** [comment]
@atherdon Okay so I have worked on the styling, which is almost complete and also added modals.
The problem is I have added a single modal to each of the link. So to assign individual modal to each link, do I do
```
this.state = {
modalForAbs: false,
modalForYoga: false,
modalForRowing: false
}
```
I mean is this the way to add indivisual modals, or is there some other simpler way?

**Comment by atherdon** [comment]
you can create one modal and when you click a link you'll pass a different
params, that will change things inside the modal. but it's more hard way.
for now i don't have preferences about how it will be done. so your way is
good for me now. but you can create a separated task, where you'll store
this text, so later we'll be able to come back to this enchancement


On 18-Jun-2018 at 10:19 PM, Sanchit Sharma wrote:


@atherdon <https://github.com/atherdon> Okay so I have worked on the
styling, which is almost complete and also added modals.
The problem is I have added a single modal to each of the link. So to
assign individual modal to each link, do I do

this.state = {
modalForAbs: false,
modalForYoga: false,
modalForRowing: false
}

I mean is this the way to add indivisual modals, or is there some other
simpler way?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/react-only-intern-23/issues/15#issuecomment-398213711>,
or mute the thread

**Comment by sanchit94** [comment]
@atherdon Okay so I have managed to get this work by adding indivisual modals to the links, I have pushed the code. Please check and suggest any modifications or improvements to this.

**Comment by atherdon** [comment]
i made some comments, please review

**Comment by sanchit94** [comment]
Alright, I'm on it.
