### ISSUE TITLE
deploy to Netlify

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/react-only-intern-23#21]
http://netlify.com

**Comment by atherdon** [comment]
please finish this task, it's easy and will increase time of my review

**Comment by atherdon** [comment]
#47

**Comment by sanchit94** [comment]
Alright... Currently working on routers, I'll do this first thing tomorrow.

**Comment by atherdon** [comment]
good. have a good night!

**Comment by sanchit94** [comment]
Thanks you too!

**Comment by sanchit94** [comment]
So I have to deploy it via making a new account in netlify or we have an account for GroceriStart?

**Comment by atherdon** [comment]
create a new acc


On 30-Jun-2018 at 09:47 AM, Sanchit Sharma wrote:


So I have to deploy it via making a new account in netlify or we have an
account for GroceriStart?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/react-only-intern-23/issues/21#issuecomment-401530424>,
or mute the thread

**Comment by sanchit94** [comment]
https://agitated-benz-377dd8.netlify.com/
Here is our deployed app.

**Comment by atherdon** [comment]
please put a link to netlify instance at repository website link


On 30-Jun-2018 at 11:46 AM, Sanchit Sharma wrote:


Closed #21 <https://github.com/GroceriStar/react-only-intern-23/issues/21>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/react-only-intern-23/issues/21#event-1709922906>,
or mute the thread

**Comment by sanchit94** [comment]
How do I do that? From netlify or github?
