### ISSUE TITLE
Modals should be as separated components

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/react-only-intern-23#27]
Put them also in one folder.
like Modal/Abs/Abs.js

**Comment by sanchit94** [comment]
So now we have just one Modal, and the data inside the modal changes as we change according to need. It is inside Modals folder. So I think you should close this one too.

**Comment by atherdon** [comment]
did you push the latest changes to PR, right? will take a look right now


On 29-Jun-2018 at 12:39 PM, Sanchit Sharma wrote:


So now we have just one Modal, and the data inside the modal changes as we
change according to need. It is inside Modals folder. So I think you should
close this one too.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/react-only-intern-23/issues/27#issuecomment-401341950>,
or mute the thread

**Comment by sanchit94** [comment]
Sure!
