### ISSUE TITLE
move styles for MealPlan into a separated styles file, related to MealPlan only

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/react-only-intern-23#28]

**Comment by sanchit94** [comment]
Okay so I am a little confused. By this do you mean a new CSS file or a js file which stores all style variables?

**Comment by atherdon** [comment]
i'm ok with js version that you did, but it can also be done by creating a separated folder for MealPlan and inside this folder create a MealPlan.scss (so we have `MealPlan` name for each of file and it's easy to understand that *.js file related to components code, *.scss related to styles, *.test.js for tests)
