### ISSUE TITLE
Meal plan next version

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/react-only-intern-23#30]
Can stuff, stored at Meal plan Form be a set with separated components, that contain related state events?
Will this reduce size of this file, right?

**Comment by sanchit94** [comment]
If the Meal Plan will have to grow in complexity then yes, separating it into components can be a good option. We can have `states ` on the `parent ` and pass it as `props ` to the `children`, what you say...

**Comment by sanchit94** [comment]
I think we should close this now?

**Comment by atherdon** [comment]
no, this will remains open while we didn't move it to a separate place.
I think Meal calendar is quite big right now. and separation will also have a good effect to the quality of code. because as you can see - groceristar-fetch is quite a small plugin and we still have issues - because we're using it in different projects

And i didn't think that this description will be quite enough for a react newbie.
just assume this example - you're trying to explain to your granny how to move this components to a new repository.
Will you add more details?
imagine how you'll do it step-by-step and describe it here. Put at least 10 steps.
