### ISSUE TITLE
Decrement & Increment Month methods

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/react-only-intern-23#32]
This methods looks a bit similar, tell me how do you think we can improve it

**Comment by sanchit94** [comment]
So shall I close this issue?

**Comment by atherdon** [comment]
i think you should google how to close github issues from git commits.
it'll help .

yes, you can close it


On 24-Jun-2018 at 10:29 PM, Sanchit Sharma wrote:


So shall I close this issue?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/react-only-intern-23/issues/32#issuecomment-399792766>,
or mute the thread
