### ISSUE TITLE
Calendar.js -> calHeaderrender()

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/react-only-intern-23#33]
I didn't like long lines like that, please update the format(just split it into few lines)

Btw, what do you think about adding a separated component for Calendar Header?

**Comment by sanchit94** [comment]
I don't think we'll use the Calender Header component anywhere else, so it is not necessary, I think the code is little messed up and not clean, so seperating header into another component can help clean up a little( not much though). However, I think it is very similar to both calRender() and calRenderCheck()

**Comment by atherdon** [comment]
if you have a few similar methods - maybe we should create a one main component, that will mimic all of this situations?

and eaah - it's better to have more small components, rather than one messy. i mean if you cannot understand what your component doing from one `view` of your eyes - then it can/should be improved

**Comment by atherdon** [comment]
check this articles, btw:
https://alligator.io/react/using-this-props-children/
https://medium.com/@js_tut/react-js-nested-components-1d08bf8806f4

**Comment by sanchit94** [comment]
Alright, I think we should seperated calHeaderRender into a different component then!! :)

**Comment by atherdon** [comment]
agree, but what about calRender and calCheck functions? as you mentioned -
header have a similar functionalities... can we improve that methods too?


On 24-Jun-2018 at 10:16 PM, Sanchit Sharma wrote:


Alright, I think we should seperated calHeaderRender into a different
component then!! :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/react-only-intern-23/issues/33#issuecomment-399791755>,
or mute the thread

**Comment by atherdon** [comment]
ok, i think we figure out the plan for this issue - you can start to work on it too

**Comment by sanchit94** [comment]
Great! I'm on it @atherdon

**Comment by atherdon** [comment]
please rename a `Calender` to `Calendar` - i think it's a mistake at medium tutorial.
Should we close this issue?

**Comment by sanchit94** [comment]
I've already changed it to `Calendar`.
