### ISSUE TITLE
pages/routing

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/react-only-intern-23#34]
https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-router

- [ ] Separate your page into 2 pages
Use router for this
Index page will be for our code from chapters(forms, our calendar, etc)
page with URL `/calendar` - will display our designed calendar

**Comment by sanchit94** [comment]
@atherdon No idea about routing, could you suggest something I can refer for studying this?

**Comment by atherdon** [comment]
https://medium.com/@pshrmn/a-simple-react-router-v4-tutorial-7f23ff27adf
https://reacttraining.com/react-router/core/guides/philosophy
https://www.youtube.com/watch?v=eofpZPRUnP8


On 27-Jun-2018 at 09:34 PM, Sanchit Sharma wrote:


@atherdon <https://github.com/atherdon> No idea about routing, could you
suggest something I can refer for studying this?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/react-only-intern-23/issues/34#issuecomment-400836529>,
or mute the thread

**Comment by atherdon** [comment]
#47

**Comment by atherdon** [comment]
sample: https://github.com/ChickenKyiv/react-menu-monkey-client/blob/master/src/routes/index.js

**Comment by atherdon** [comment]
ok, closing this
