### ISSUE TITLE
Day component

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/react-only-intern-23#41]
maybe move it into separated file?

**Comment by atherdon** [comment]
#47

**Comment by sanchit94** [comment]
So by this you mean move `getOffset` and `rendererFunc` to a different file?

**Comment by atherdon** [comment]
I mean that we has a few components inside one file. so i want to move it into a separated file

**Comment by atherdon** [comment]
i think it's done, right? if yes- please close it

**Comment by sanchit94** [comment]
Yes it's done!
