### ISSUE TITLE
MealPlan -> renderMeals

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/react-only-intern-23#42]
What do you think if we'll move a Meal Card into a separated component?

**Comment by sanchit94** [comment]
Yes I'm with that option. Also I think instead of different arrays meal, imgURL, description and steps, we can make it into an array of objects containing keys mealName, imgURL, etc. This way info will be more meaningful and I think we will need less handler functions

**Comment by atherdon** [comment]
sure

**Comment by atherdon** [comment]
then create a 3 different version of cards
- [ ] current version
- [ ] without image
- [ ] all data related to meal should display in this card

+ add button - "View Meal" - later it'll be a route to a meal details page

**Comment by atherdon** [comment]
#47

**Comment by sanchit94** [comment]
Okay working on this one now, but I think now I should start writing tests for our components. Will do that after this one!

**Comment by sanchit94** [comment]
@atherdon I am okay with the second version, but for the third version, wouldn't that be too much data in a single card as it will defeat the purpose of the card. I think what we should do is have the current version of the card and when user clicks on it, modal should pop up which displays all data.

**Comment by atherdon** [comment]
don't worry - you'll dig it later. it'll help us on other projects, so maybe right now it looks not very necessary, but for other cases - it'll be a good improvement

**Comment by sanchit94** [comment]
Okay so the code will be reused, cool!

**Comment by atherdon** [comment]
sure, i want to make this code available for other developers of food
startups too! we should create code for robots, not only recipe webisites
:)


On 02-Jul-2018 at 07:37 PM, Sanchit Sharma wrote:


Okay so the code will be reused, cool!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/react-only-intern-23/issues/42#issuecomment-401911197>,
or mute the thread
