### ISSUE TITLE
More Tests! :)

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/react-only-intern-23#57]
![xxx](https://media.giphy.com/media/yoJC2GnSClbPOkV0eA/giphy.gif)

**Comment by atherdon** [comment]
please follow this link in order to get access to react-search-form repo: https://github.com/ChickenKyiv/recipe-search-react/invitations

**Comment by sanchit94** [comment]
Tests in this repo don't use enzyme. Should I write tests using shallow or go with render?

**Comment by atherdon** [comment]
just add enzyme


On 04-Jul-2018 at 10:54 AM, Sanchit Sharma wrote:


Tests in this repo don't use enzyme. Should I write tests using shallow or
go with render?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/react-only-intern-23/issues/57#issuecomment-402443828>,
or mute the thread

**Comment by atherdon** [comment]
i think you'll like this article too: https://medium.com/quick-code/basic-requirements-for-react-native-app-8820067e1c50

**Comment by sanchit94** [comment]
Thank you very much Arthur, this article was of great help.

**Comment by sanchit94** [comment]
Great!!

**Comment by atherdon** [comment]
https://github.com/GroceriStar/playing-with-graphql/issues/7
