### ISSUE TITLE
use recipes data from groceristar-fetch

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/react-only-intern-23#59]
- [x] install our package by `npm install @groceristar/groceristar-fetch`

We cannot move forward, while we didn't have static data, related to recipes in our module

**Comment by sanchit94** [comment]
I think this one is done partially now!

**Comment by atherdon** [comment]
Nah, you just find a data from search-form/search-api.
This tasks is related to data that we need: GroceriStar/groceristar-fetch#26
GroceriStar/groceristar-fetch#2 and we didn't started them yet @sanchit94

**Comment by atherdon** [comment]
i got a PR from guy that working on `fetch` plugin, and when i'll publish the newest version of this plugin - we'll be able to get that data from our plugin

**Comment by atherdon** [comment]
GroceriStar/groceristar-fetch#2

**Comment by atherdon** [comment]
@sanchit94  i add some code to your repo. i think now you can use data from groceristar-fetch plugin and display in on your project

**Comment by sanchit94** [comment]
Hey @arthur,  I was away for a couple of days, so couldn't work on the
project. I'll have a look and push the code soon!! :)

**Comment by atherdon** [comment]
it's ok, not a problem. i was just reviewing the issues for different repos and update some of them

**Comment by sanchit94** [comment]
Hey @atherdon I was just looking at the code you added, the RecipeTest component. So what will we be doing with this data? Do you want to me to create a component(card) where this data will be displayed?

**Comment by sanchit94** [comment]
Also I was wondering, when would we use http requests. I mean when I add a meal using the addMealModal, I should be sending a request to the server with this data. I think this will be a good added function to our repo! Please advice! :)

**Comment by atherdon** [comment]
yeah. i was thinking about it too.
the main trouble - 2 of our servers are working weird right now.

i assume third(server with recipes) still working fine. but as we decided to move to graphQL - i think it'll better to connect to database by using graphQL approach.
tell me - did you finish that graphQL course? if yes - we can start to build a graphQL schemas, and then we'll be able to send requests from your form to graphQL instance

**Comment by sanchit94** [comment]
Yes I finished that course(almost). :p

**Comment by sanchit94** [comment]
Let's start a task in this direction. Maybe we'll make slow progress but that's better than no progress.

**Comment by atherdon** [comment]
i didn't think that we'll make a slow progress with it.
first of all - broken servers are in my priority list.
second thing - as you can see - i add a lot of people to that repository,
so i hope together we'll make it quick. another thing - i have a lot of
data, so it'll be more easy to redo, rather than create it from 0 as i did
year ago.

another point - it's a cool technoogy and i want to include it.


On 31-Jul-2018 at 09:17 PM, Sanchit Sharma wrote:


Let's start a task in this direction. Maybe we'll make slow progress but
that's better than no progress.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/react-only-intern-23/issues/59#issuecomment-409370933>,
or mute the thread

**Comment by sanchit94** [comment]
Yea I think it is pretty cool, would get a better perspective regarding it when I actually work on it.  :)
