### ISSUE TITLE
small components

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/react-only-intern-23#71]
replace components for allergy and other similar like diets, etc(you can tell me which recipe fields do you think is attributes).

+ i think we should have a separated place for wrapper Group tag. i mean if we have to make our components very clean and separated - we should remove all data, that add additional weight on it.
let's discuss it here
+ we can create a one select field for each of items that we have selects inside

**Comment by sanchit94** [comment]
@atherdon Okay so you want me to do something like you've done in recipy-search-react repo, where you have an Attribute component, which acts like wrapper?

**Comment by atherdon** [comment]
maybe, but not exactly. but yach - my way is ok, because i tried to avoid duplication as much as possible
the problem is that my code at recipe-search-form is still not working. i mean don't have a lot of time to finish it.
You can try to do it my way, but not broke everything :)

**Comment by sanchit94** [comment]
@atherdon I am pushing some code please check if it looks good.

**Comment by atherdon** [comment]
let's go with Attribute way, not sure but maybe this will be not a problem later, when we'll use GraphQL
