### ISSUE TITLE
gs=fetch work on your side

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/react-only-intern-23#92]
can you test it or show me the code line how do you connect it?

**Comment by atherdon** [comment]
Ok, i find this code line.
https://github.com/GroceriStar/react-only-intern-23/blob/master/src/component/FormFields/Attribute.js#L88

It was hard, because i think we need to improve structure for our forms.
I mean we have form in `meal planning` folder, which is not clear
form elements we have at another separated `FormFields` folder - i think it's a bit complicated.

Btw, looks like it works ok on your side. and i like select-boxes that you have at addMealForm.
I was able to take a quick look on it.

One more thing: i didn't adore that long line at attribute render() - really hard to catch what is going on inside. 

But i like our pace. i plan a big comeback soon, so maybe will be able to help you with components, related to recipes, ingredients, etc.

**Comment by atherdon** [comment]
the reason why i asked: at recipe-search form i was not able to `hack` it. and was so upset so decided to start rewriting groceristar-fetch with es6 approach. but as it works well - i can pause it and back to it later

**Comment by sanchit94** [comment]
Great! actually my computer broke again, it's kinda getting annoying! Working on windows 7 for a bit.

**Comment by sanchit94** [comment]
With new react-select options does not have to be a state necessarily, and regarding the long line, I just used it because Attribute's test was failing, so it was some sort of temporary fix, I'll improve the code.

**Comment by sanchit94** [comment]
Btw I also think that we should remove the unused components now like diets, holidays etc. They are just polluting the codebase now as we are not using them anywhere.

**Comment by atherdon** [comment]
sure, please do it. as clean as it should be.


On 31-Jul-2018 at 08:48 AM, Sanchit Sharma wrote:


Btw I also think that we should remove the unused components now like
diets, holidays etc. They are just polluting the codebase now as we are not
using them anywhere.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GroceriStar/react-only-intern-23/issues/92#issuecomment-409145245>,
or mute the thread

**Comment by atherdon** [comment]
closing this task
